---
title: "Assignments"
---

## Ground rules for assignments

* Unless otherwise stated, you may work on assignments **individually** or in **pairs**, and your choice may change from one assignment to the next.  
* For each assignment, I will create a **group set in Canvas**; you will sign up to form your group.  
* **Only one person per group submits** the assignment in Canvas. The submission is automatically shared with all group members.  
* Grades and feedback are shared with the whole group. By default, all members receive the **same grade**.  
* Assignments are due by **11:59 PM** on the due date.  
* Each submission must include **all relevant files**:

  1. A self-contained, working copy of any code used  
     **AND**
  2. A PDF version of item 1, including the output, plus any analytic work.  
     - Legible handwriting and typed work are both acceptable.
     - You may embed the analytic work as markdown in the code if you wish.
 
## List of assignments

| Assignment     | Due Date
|-------------------------------------|-----------|
| Assignment 1 — Diagnostic survey (Canvas / Microsoft Forms) | January 16
| Assignment 2 — {{< meta course.textbook.short >}} 3.9, 3.28d, 4.26, 5.8, <br> Find and submit a screenshot, photo or pdf of a statistical claim that you find somewhere in public. Write a paragraph describing what questions you might have about the origin or interpretation of this statistical claim. | January 30