---
title: "Schedule"
---

Classes are normally held in RE 102 at 10 AM on Tuesdays and Thursdays

### January

| Week | Date   | Topic                    | Slides                             |
|-|--------|---------------------------|-------------------------|
| 1 | Tue Jan 13 | Introductory Examples,  Course Overview | [Introduction and Probability Review](../slides/01-intro.html)  |
|  | Thu Jan 15 | Introductory Examples, Key Probability Concepts |    
|  | Fri Jan 16 | **Diagnostic Survey Due**                                |
| 2 | Tue Jan 20 | Key Probability Concepts, Important Distributions, Conditional Probability | |
|  | Thu Jan 22 | Conditional Probability, Convergence, Central Limit Theorem | |
| 3 | Tue Jan 27 | Central Limit Theorem, Chebyshev's Inequality, Summary Statistics| [Estimation and Confidence Intervals](../slides/02-estimator.html) | |
|  | Thu Jan 29 |  Summary Statistics, Maximum Likelihood Estimation, Bias, Mean Squared Error | |
### February

| Week | Date   | Topic                    | Slides                             |
|-|--------|---------------------------|-------------------------|
|  | Fri Jan 30 | **Assignment 2 Due**
| 4 | Tue Feb 3 | Distributions of estimators | |
|  | Thu Feb 5 | Confidence intervals | |
| 5 | Tue Feb 10 | Confidence intervals for means | |
|  | Thu Feb 12 | Confidence intervals for variances, Bootstrap confidence intervals| |
|  | Fri Feb 13 | **Assignment 3 Due**
| 6 | Tue Feb 17 | Sufficient statistics and related topics | |
|  | Thu Feb 19 | Completeness, Rao-Blackwell, Cramér-Rao lower bound, exponential families| |
| 7 | Tue Feb 24 | Prediction and tolerance intervals, hypothesis testing| [Hypothesis Testing](../slides/03-hypothesis.html)
|  | Thu Feb 26 | **Test 1** | |
### March

| Week | Date   | Topic                    | Slides                             |
|-|--------|---------------------------|-------------------------|
| 8 | Tue Mar 3 | Hypothesis testing examples, likelihood ratio tests | |
|  | Thu Mar 5 | Likelihood ratio tests | |
|  | Fri Mar 6 | **Project Submission Due** | |
| 9 | Tue Mar 10 | Review of concepts, look at Test 1, linear models| [Linear Models](../slides/04-linear_models.html)|
|  | Thu Mar 12 | Ordinary least squares | |
|  | Fri Mar 13 | **Assignment 4 Due** | |
|  | Tue Mar 17 | **No Class, Spring Break** | |
|  | Thu Mar 19 | **No Class, Spring Break** | |
| 10 | Tue Mar 24 | Ordinary least squares and inference | |
|  | Thu Mar 26 | | Ordinary least squares inference and diagnostics  |
| 11 | Tue Mar 31 | | |
### April

| Week | Date   | Topic                    | Slides                             |
|-|--------|---------------------------|-------------------------|
|  | Thu Apr 2 | | |
| 12 | Tue Apr 7 | **Test 2** on Optimality of Estimators, Hypothesis Testing, and Ordinary Least Squares Through Inference | |
|  | Thu Apr 9 | | |
| | Fri Apr 10 | **Assignment 5 Due** | |
| 13 | Tue Apr 14 | | |
|  | Thu Apr 16 | | |
| 14| Mon Apr 20 | **Project Presentation** in Galvin Tower 14th Floor West Side Conference Room | |
| | Tue Apr 21 | **Project Presentation** in Galvin Tower 14th Floor West Side Conference Room | |
| | Wed Apr 22 | **Project Presentation** in Galvin Tower 14th Floor West Side Conference Room | |
| | Thu Apr 23 | | |
| 15 | Tue Apr 28 | | |
| | Thu Apr 30 | | |
### May

| Week | Date   | Topic                    | Slides                             |
|-|--------|---------------------------|-------------------------|
| 16 | Tue May 5 | **Final Exam** in HH 003 | |
